# .github/dependabot.yml

version: 2
updates:
  # Maintain dependencies for the template project itself (pdm)
  - package-ecosystem: "pip"
    directory: "/"  # Location of pyproject.toml
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Only automerge non-major updates
    versioning-strategy: increase-if-necessary
