repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]  # Add any types your project needs
      - id: commitizen-prepare-commit-msg
        name: commitizen prepare-commit-msg
        # The script to execute.
        entry: python prepare-commit-msg.py
        # The programming language of the script.
        language: python
        # The git hook stage to run on.
        additional_dependencies: [commitizen]
        stages: [prepare-commit-msg]
        # Ensure it runs even if files are not staged.
        always_run: true
        # Helps with debugging if needed.
        verbose: true
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen-branch
        stages: [pre-push]
